spring:
  profiles:
    active: dev
    include: rabbitmq, redis
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${DB_PW}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  upload:
    dir: ${UPLOAD_DIR}
  mail:
    username: ${MAIL_USER}
    password: ${MAIL_PW}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp.auth: true
        smtp.timeout: 50000
        smtp.starttls.enable: true
application:
  jwt:
    refresh-exp: ${REFRESH_EXP}
    access-exp: ${ACCESS_EXP}
    prefix: Bearer
    header: Authorization
    secretKey: ${SECRET_KEY}
springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
    path: /v3/api-docs

  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html
dauth:
  client_id: ${DAUTH_ID}
  client_secret: ${DAUTH_SECRET}
cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    region:
      static: AP_NORTHEAST_2 # 서울 리전
    stack:
      auto: false
    credentials:
      secret-key: ${AWS_IAM_SECRET}
      access-key: ${AWS_IAM_ACCESS}

server:
  port: 8085